version: '3.7'

services:
  surging.test.server:
    environment:
      LogPath: /app/configs/log4net.config
    volumes:
      - ../test/Surging.Test.Server/configs:/app/configs
      - ../src/annotationxmldir:/app/annotationxmldir
  surging.test.client:
    environment:
      LogPath: /app/configs/log4net.config
    volumes:
      - ../test/Surging.Test.Client/configs:/app/configs
      - ../src/annotationxmldir:/app/annotationxmldir