version: '3.7'

services:
  surging.hero.auth:
    environment:
      LogPath: /app/configs/log4net.config
    volumes:
      - ../../src/Shared/Configs:/app/configs
      - ../annotationxmldir:/app/annotationxmldir

  surging.hero.basicdata:
    environment:
      LogPath: /app/configs/log4net.config
    volumes:
      - ../../src/Shared/Configs:/app/configs
      - ../annotationxmldir:/app/annotationxmldir

  surging.hero.organization:
    environment:
      LogPath: /app/configs/log4net.config
    volumes:
      - ../../src/Shared/Configs:/app/configs
      - ../annotationxmldir:/app/annotationxmldir
  surging.hero.gateway:
    volumes:
      - ../../src/Shared/Configs:/app/configs
