version: '3.7'

services:  
  hero.redis:
    image: redis:latest
    restart: always
    ports:
      - "16379:6379"
    networks:
      - surging_hero_service_net

  hero.rabbitmq:
    image: rabbitmq:management
    restart: always
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      - surging_hero_service_net

  hero.mysql:
    image: mysql:8.0.15
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "qwe!P4ss"
      MYSQL_PASSWORD: "qwe!P4ss"
    volumes:
      - ./.mysql/data:/var/lib/mysql
      - ../../db/sql:/docker-entrypoint-initdb.d

    ports:
      - "3306:3306"
    networks:
      - surging_hero_service_net
      
networks:
  surging_hero_service_net: 
    driver: bridge
    name: surging_hero_service_net
    ipam:
      driver: default
      config:
      - subnet: 172.23.0.1/16